name: ditonton

packages:
  - movie
  - tv
  - core
  
scripts:
  test:
    # Only run the test command when the package has a test directory
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages